package com.stockanalysis.model.event;

public enum AnalysisStage {
    RESEARCHER_STARTED, RESEARCHER_COMPLETED,
    TECHNICAL_STARTED, TECHNICAL_COMPLETED,
    SENTIMENT_STARTED, SENTIMENT_COMPLETED,
    INVESTMENT_MANAGER_STARTED, INVESTMENT_MANAGER_COMPLETED,
    BULL_STARTED, BULL_COMPLETED,
    BEAR_STARTED, BEAR_COMPLETED,
    NEUTRAL_STARTED, NEUTRAL_COMPLETED,
    ARBITRATOR_STARTED, ARBITRATOR_COMPLETED,
    ANALYSIS_COMPLETED, ANALYSIS_FAILED
}
